apiVersion: v1
kind: Service
metadata:
  name: myapp-clusterip-svc
spec:
  type: ClusterIP
  ports:
  - port: 8081 #service port
    targetPort: 8081 # pod/container running port
  selector:
    app: myapp