---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-frontend
spec:
  template:
    metadata:
      labels:
        app: httpd-frontend
    spec:
      containers:
        - name: htppd-container
          image: httpd:2.4-alpine
  replicas: 2
  selector:
    matchLabels:
      app: httpd-frontend